# Step 1: Use a lightweight JRE image for the runtime
FROM eclipse-temurin:17-jre-alpine

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy the JAR file generated by Maven into the container
# Ensure you have run 'mvn package' before building the docker image
COPY target/*.jar app.jar

# Step 4: Expose the port the app runs on (standard for Spring/Java)
EXPOSE 8080

# Step 5: Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
